version: '3.8'

services:
  intro:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
  db:
    image : mongo
    container_name: intro-mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./.database/mongo:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped